version: "3.9"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: es
    hostname: es
    networks:
      - malicious-net-12
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  elastic_search:
    image: avigoldshtein/week_12_elastic_search_malicious_text:latest
    ports:
      - "8000:8000"
    networks:
      - malicious-net-12
    environment:
      - ELASTIC_HOST=es
      - ELASTIC_PORT=9200
    depends_on:
      es:
        condition: service_healthy

networks:
  malicious-net-12:
